### ISSUE TITLE
Contact form verbeteren op basis van toegankelijkheid en (pleasurable) usability

### ISSUE THREAD

**Issue by Annevd** [fdnd-agency/buurtcampus-oost#216]
Zie [projectplan](https://github.com/fdnd-agency/buurtcampus-oost/issues/198).

**Comment by Annevd** [comment]
## Fixed contrast

Ik heb de input fields een outline gegeven om het contrast tussen de achtergrond en het input field duidelijker te maken.

### **Before/After:**

<img width=300 src="https://github.com/user-attachments/assets/efabdb93-fb19-4f13-b0e5-3be448db1cfd">
<img width=300 src="https://github.com/user-attachments/assets/0a5fbd48-e3bd-47dc-b04f-24deb7f277a2">

<img width=300 src="https://github.com/user-attachments/assets/0fc1b0b7-eddf-496b-ac68-63faf1de2b90">
 
Zoals te zien is dit voor grafische elementen hoog genoeg.

Ook heb ik de placeholder tekst iets donkerder gemaakt zodat dat contrast op de witte achtergrond hoog genoeg was.

**Code:**

```CSS
.fields-container input[type='text'],
.fields-container input[type='email'],
.fields-container textarea { 
    outline: 1px solid var(--input-border-color); /* outline */
    border: none;
    padding: 0.5rem;
    border-radius: var(--border-card);
    width: 100%;
}

### ::placeholder {
    color: #545454; /* donkerdere placeholder tekstkleur */
}
```
