### ISSUE TITLE
Creative coding spike 1: Bouwen

### ISSUE THREAD

**Issue by Annevd** [fdnd-agency/buurtcampus-oost#253]
**Stappenplan (basic --> advanced):**
- [x] Saturation gaat omlaag hoe verder je scrollt
- [x] Elementen vallen om hoe verder je scrollt
- [x] Cracks verschijnen in de elementen en worden steeds meer en zichtbaarder hoe verder je scrollt
- [x] Planten/klimops zullen steeds meer verschijnen hoe verder je scrollt
- [ ] Elementen zullen afbrokkelen hoe verder je scrollt (mask:)

**Comment by Annevd** [comment]
## Desaturate when scrolling

**Stap 1** was om voor elkaar te krijgen dat hoe verder je over de pagina scrolt, hoe minder gesatureerd de pagina wordt. Dit laat zien dat de website ouder en fragieler wordt (mysterious & post-apocalyptic).

Om dit te doen ben ik begonnen met het maken van een simpele keyframe animatie die de saturatie veranderd van 100% aan het begin, naar 10% op het einde:
```CSS
@keyframes desaturate {
    0% {
        filter: saturate(1);
    }
    100% {
        filter: saturate(10%);
    }
}
```

Omdat ik wil dat de volledige website/pagina veranderd, zet ik de scroll driven animatie op het `html` element:
```CSS
html {
/* de @supports zorgt ervoor dat het alleen toegepast wordt wanneer de browser het support */
	@supports (animation-timeline: scroll()) { 
		animation: desaturate linear; /* past de animatie linear toe, zonder easing dus */
		animation-timeline: scroll(root y); /* verticale scroll op de root */
	}
}
```
Voor deze animatie gebruik ik `scroll()` i.p.v. `view()` omdat ik de animatie wil koppelen aan de scrollpositie van de pagina in plaats van de zichtbaarheid van het element in de viewport. Hiermee kan ik de animatie baseren op hoe ver je hebt gescrold in de viewport.

**Comment by Annevd** [comment]
## Elements crack when scrolling

**Stap 2** lukte nog niet goed, dus ben ik alvast verder gegaan met stap 3. Ik heb nu gebouwd dat bepaalde elementen en sections scheuren hebben, en deze zichtbaarder worden hoe verder je op de pagina scrollt.

Ik ben ook hier weer begonnen met het maken van een keyframe animatie die de `opacity` behandelt:
```CSS
@keyframes opacity {
	0% {
	    opacity: 0;
	}
	100% {
	    opacity: 100%;
	}
}
```
Elke section heeft een `::after` met daarin verschillende background images van scheuren. Door de scroll driven animatie op die `::after`s te zetten, zal de `opacity` van deze scheuren zichtbaarder worden hoe verder je scrollt over de pagina.

```CSS
footer::after {
        content: "";
        position: absolute;
        inset: 0;
        background-image: 
            url('/assets/crack1.png'), /* verschillende scheur png's*/
            url('/assets/crack2.png'),
            url('/assets/crack1.png'),
            url('/assets/crack4.png');
        background-position: /* positie van de png's */
            top right,
            bottom right,
            bottom left,
            center; 
        background-size: /* grootte van de png's */
            40%, 
            30%,
            50%;
        background-repeat: no-repeat;
        z-index: 1000;

/* de @supports zorgt ervoor dat het alleen toegepast wordt wanneer de browser het support */
        @supports (animation-timeline: scroll()) { 
            animation: opacity linear; /* past de animatie linear toe, zonder easing dus */
            animation-timeline: scroll(root y);  /* verticale scroll op de root */
	    }
    }
```
