### ISSUE TITLE
Plant animatie bij valid input op form toepassen

### ISSUE THREAD

**Issue by Annevd** [fdnd-agency/buurtcampus-oost#258]

**Comment by Annevd** [comment]
## Plant animatie bij focus/valid

Wanneer je als gebruiker klikt in de input om te gaan typen, verschijnt er een deel van een plante van onder de input vandaan. Wanneer de gebruiker naar de volgende input gaat, en de vorige input valid is ingevuld, komt het volledige plantje met een animatie tevoorschijn.

Om dit te maken ben ik begonnen een `div` om de inputs en labels heen te zetten. Dit zorgt ervoor dat ik de plantjes relatief aan deze div kan positioneren bij elke input.

```HTML
<div>
      <label for="name">Voornaam:</label>
      <input type="text" id="name" name="name" placeholder="Voer je voornaam in" required/>
</div>
```
De `div` geef ik `position: relative;`, zodat ik de plantjes kan positioneren ten opzichte van deze div.
```CSS
div {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
    position: relative;
}
```
Vervolgens zet ik een `::after` op de `div`, deze krijgt een background-image van mijn plant svg.

```CSS
fieldset div::after {
    content: "";
    position: absolute;
    top: -0.15rem;
    right: 10px;
    width: 40px;
    height: 40px;
    scale: 0.5; /* maakt het plantje kleiner zodat het niet zo zichtbaar is */
    background-image: url('/src/lib/assets/plant.svg');
    background-size: contain;
    background-repeat: no-repeat;
    opacity: 0; /* standaard is de svg niet zichtbaar */
    z-index: 10;
    transform: translateY(100%); /* dit verplaatst het plantje naar beneden, zodat het omhoog kan springen na focus/valid */
    transition: all 0.5s cubic-bezier(.75,-0.5,0,1.75); /* door deze transition krijgt het plantje een leuke bounce  wanneer het omhoog */
}
```
Vervolgens zeg ik hier dat wanneer de div een valid input heeft, dat het plantje weer zichtbaar en de normale grootte moet worden, en omhoog moet komen. Wanneer de input gefocust is, komt het plantje half tevoorschijn (20%).
```CSS
/* Valid */

fieldset div:has(input:valid)::after {
    opacity: 1;
    scale: 1;
    transform: translateY(0);
}

/* Focus */

fieldset div:has(input:focus)::after,
fieldset div:has(input:focus:valid)::after {
    transform: translateY(20%);
    opacity:1;
    scale: 1;
    transition-delay: .3s; /* zorgt ervoor dat het plantje pas na 0.3s seconden tevoorschijnkomt */
}
```
