### ISSUE TITLE
Footer mobiel responsive

### ISSUE THREAD

**Issue by Lmikkers** [fdnd-agency/buurtcampus-oost#344]
Responsive maken voor mobiel, `justify content` uitzetten

**Comment by Lmikkers** [comment]
> ✅  Dit is opgelost! 

``` css
@media (max-width: 43.75em) {
   footer {
      justify-content: unset;
   }
}

```

### Before
<img width="324" alt="Image" src="https://github.com/user-attachments/assets/2197939f-f836-4cc7-a8ce-ba24db81b2bc" />

### After
<img width="324" alt="Image" src="https://github.com/user-attachments/assets/01c01834-b1f2-4251-9684-985fbb6409a6" />
